import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "../globals.css";
import InitApp from "@/components/InitApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BRC20 Minter Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={params?.lang || 'en'} data-theme="lofi">
      <head>
        <Script
          async
          src="/assets/telegram-web-app.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className}>
        {children}
        <InitApp />
      </body>
    </html>
  );
}
